states:
  - name: UserMessage
    class: src.states.base.UserMessage
  - name: AssistantMessage
    class: src.states.base.AssistantMessage
  - name: Finished
    class: src.states.base.Finished
  - name: ToolCall
    class: src.states.advanced.ToolCall
  - name: WaitingForToolResult
    class: src.states.advanced.WaitingForToolResult
  - name: ToolResult
    class: src.states.advanced.ToolResult
  - name: AgentCall
    class: src.states.advanced.AgentCall
  - name: WaitingForAgentResult
    class: src.states.advanced.WaitingForAgentResult
  - name: AgentResult
    class: src.states.advanced.AgentResult
  - name: ToolFailureState
    class: src.states.error_states.ToolFailureState
  - name: AgentFailureState
    class: src.states.error_states.AgentFailureState
  - name: TimeoutState
    class: src.states.error_states.TimeoutState
  - name: ClarificationState
    class: src.states.base.ClarificationState

tools:
  - name: calculator
    class: src.integrations.tools.tool_registry.CalculatorTool
  - name: test_tool
    class: src.integrations.tools.tool_registry.TestTool
