states:
  - name: UserMessage
    class: src.states.base.UserMessage
  - name: AssistantMessage
    class: src.states.base.AssistantMessage
  - name: Finished
    class: src.states.base.Finished
  - name: ToolResult
    class: src.states.advanced.ToolResult
  - name: AgentResult
    class: src.states.advanced.AgentResult
